ShifterAndWorker/SAW.UI/Areas/Panel/Controllers/NoteController.cs
using SAW.BLL.UnitOfWork;
using SAW.DAL.Context;
using SAW.Model.ViewModel;
using SAW.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAW.UI.Areas.Panel.Controllers
{
    [CustomAuthorization]
    public class NoteController : Controller
    {
        //readonly ShifterAndWorkerEntities _context;
        //readonly UnitOfWork _uow;

        //public NoteController()
        //{
        //    _context = new ShifterAndWorkerEntities();
        //    _uow = new UnitOfWork(_context);
        //}

        private IUnitOfWork _uow;

        public NoteController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public ActionResult List()
        {
            User loggedUser = Session["LoggedUser"] as User;

            var notes = _uow.NoteManager.ListAll(x => x.IsActive && x.UserId == loggedUser.UserId).OrderByDescending(x => x.CreateDate).ToList();
            List<VMNote> vmNote = VMNote.Parse(notes);

            return View(vmNote);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Edit(int id)
        {
            User loggedUser = Session["LoggedUser"] as User;

            Session["SelectedNoteId"] = id; // Created to capture in post method when data is sent.

            Note note = _uow.NoteManager.Get(x => x.NoteId == id && x.UserId == loggedUser.UserId);
            if (note == null)
            {
                TempData["ProcessResult"] = "There was an error while viewing the note.";
                TempData["AlertType"] = "danger";
                return RedirectToAction("List");
            }

            VMNote vmNote = VMNote.Parse(note);
            return View(vmNote);
        }
        public JsonResult Delete(int id)
        {
            JsonResult jsonResult = new JsonResult
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

            var result = _uow.NoteManager.Delete(id);
            if (_uow.SaveChanges())
            {
                jsonResult.Data = new
                {
                    success = result,
                    message = result.Message,
                };
                return jsonResult;
            }
            else
            {
                jsonResult.Data = new
                {
                    success = result.Success,
                    message = result.Message,
                };
                return jsonResult;
            }
        }

        [HttpPost]
        public ActionResult Create(Note model)
        {
            User loggedUser = Session["LoggedUser"] as User;

            model.UserId = loggedUser.UserId;
            model.CreateDate = DateTime.Now;
            model.IsActive = true;

            _uow.NoteManager.Add(model);
            if (!_uow.SaveChanges())
            {
                TempData["ProcessResult"] = "An unexpected error occurred while creating the note.";
                TempData["AlertType"] = "danger";
                return RedirectToAction("List");
            }

            TempData["ProcessResult"] = "Note created successfully.";
            TempData["AlertType"] = "success";
            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Edit(VMNote model)
        {
            User loggedUser = Session["LoggedUser"] as User;
            int selectedNoteId = Convert.ToInt32(Session["SelectedNoteId"]);

            Note note = _uow.NoteManager.Get(x => x.NoteId == selectedNoteId && x.UserId == loggedUser.UserId);
            note.Title = model.Title;
            note.Body = model.Body;
            note.UpdateDate = DateTime.Now;

            var result = _uow.NoteManager.Update(note);

            Session.Remove("SelectedNoteId");
            if (!_uow.SaveChanges())
            {
                TempData["ProcessResult"] = "An enexpected error occurred while updating the note.";
                TempData["AlertType"] = "danger";
            }

            TempData["ProcessResult"] = "Note updated successfully.";
            TempData["AlertType"] = "success";
            return RedirectToAction("List");
        }
    }
}

ShifterAndWorker/SAW.UI/Areas/Panel/Views/Note/Create.cshtml
@{
    ViewBag.Title = "Create Note";
    Layout = "~/Areas/Panel/Views/Shared/_Layout.cshtml";
}

<div style="margin: 100px 50px;">
    <div class="header">
        @*<a class="btn btn-xs btn-dark" href="/Panel/Note/List"><i class="fa fa-arrow-circle-left"></i> Back To List</a>*@
        <h1><strong>Create</strong> Note</h1>
        <hr />
    </div>
    <div class="row">
        @if (TempData["ProcessResult"] != null)
        {
            <div class="alert alert-@TempData["AlertType"]" role="alert">
                @TempData["ProcessResult"].ToString()
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "Note", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="row m-t-10">
                    <div class="col-xs-3">

                        <div class="form-group">
                            <label class="control-label">Title*</label>
                            <div class="append-icon">
                                <input type="text" name="title" class="form-control form-white" autocomplete="off" maxlength="100" autofocus required />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Body*</label>
                            <div class="append-icon">
                                <textarea class="form-control form-white" name="body" style="resize:vertical;" rows="10"  autocomplete="off" required></textarea>
                            </div>
                        </div>

                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ShifterAndWorker/SAW.UI/Areas/Panel/Views/Note/Edit.cshtml
@using SAW.Model.ViewModel
@model VMNote

@{
    ViewBag.Title = "Edit Note";
    Layout = "~/Areas/Panel/Views/Shared/_Layout.cshtml";
}

<div style="margin: 100px 50px;">

    <div class="header">
        <a class="btn btn-xs btn-dark" href="/Panel/Note/List"><i class="fa fa-arrow-circle-left"></i> Back To List</a>
        <h1><strong>Edit</strong> Note</h1>
        <hr />
    </div>
    <div class="row">

        @if (TempData["ProcessResult"] != null)
        {
            <div class="alert alert-@TempData["AlertType"]" role="alert">
                @TempData["ProcessResult"].ToString()
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="col-lg-12">
            @using (Html.BeginForm("Edit", "Note", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="row m-t-10">
                    <div class="col-xs-3">
                        <div class="form-group">
                            <label class="control-label">Title*</label>
                            <div class="append-icon">
                                <input type="text" name="title" value="@Model.Title" class="form-control form-white" maxlength="100" autocomplete="off" autofocus required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Body*</label>
                            <div class="append-icon">
                                <input type="text" name="body" value="@Model.Body" class="form-control form-white" autocomplete="off" />
                            </div>
                        </div>
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ShifterAndWorker/SAW.UI/Areas/Panel/Views/Note/List.cshtml
@using SAW.Model.ViewModel
@model List<VMNote>

@{
    ViewBag.Title = "Note List";
    Layout = "~/Areas/Panel/Views/Shared/_Layout.cshtml";
}

<!-- BEGIN PAGE CONTENT -->
<div class="page-content page-thin">
    <div class="row">
        <div class="col-lg-12 portlets">
            <div class="alert" role="alert" id="postResult" style="        display: none">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if (TempData["ProcessResult"] != null)
            {
                <div class="alert alert-@TempData["AlertType"]" role="alert">
                    @TempData["ProcessResult"].ToString()
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }

            <a href="/Panel/Note/Create" class="btn btn-sm btn-dark"><i class="fa fa-plus"></i> Create New Note</a>
            <div class="panel">
                <div class="panel-header">
                    <h3><i class="fa fa-table"></i> <strong>Note</strong> Table</h3>
                </div>
                <div class="panel-content">
                    <table class="table table-hover">

                        <tbody>
                            @{
                                foreach (var note in Model)
                                {

                                    <div class="col-sm-4">
                                        <div class="card" style="max-width: 20rem;">
                                            <div class="card border-top"></div>
                                            <div class="card-text"><h6 class="completed-date" style="text-align: left;">@note.CreateDate</h6></div>
                                            <div class="card-header">@note.Title</div>
                                            <div class="card-body">
                                                <p class="card-text">@note.Body</p>
                                                <a class="edit btn btn-sm btn-default" style="text-align:right;" href="/Panel/Note/Edit/@note.NoteId" data-rel="tooltip" data-original-title="Edit"><i class="icon-note"></i>Edit</a>
                                                <button class="delete btn btn-sm btn-danger" style="text-align:right;" onclick="deleteNote(@note.NoteId)" data-rel="tooltip" data-original-title="Delete">Delete <i class="icons-office-52"></i></button>

                                            </div>
                                            <div class="card border-bottom"></div>
                                        </div>
                                    </div>

                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT -->
<script>
    function deleteNote(noteId) {
        if (confirm("Are you sure you want to delete this note?")) {
            $.ajax({
                url: "/Panel/Note/Delete",
                type: "POST",
                data: { id: noteId },
                success: function (data) {
                    if (data.success) {
                        alert(data.message)
                        location.reload();
                    }
                    else
                        $("#postResult").addClass("alert-danger").append(data.message).show();
                }
            });
        }
    };
</script>