ShifterAndWorker/SAW.UI/Areas/Panel/Controllers/ShiftController.cs
using SAW.BLL.UnitOfWork;
using SAW.Core;
using SAW.DAL.Context;
using SAW.Model.ViewModel;
using SAW.UI.Filters;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAW.UI.Areas.Panel.Controllers
{
    [CustomAuthorization]
    public class ShiftController : Controller
    {
        private IUnitOfWork _uow;
        private ShifterAndWorkerEntities _context;

        public ShiftController(IUnitOfWork uow)
        {
            _uow = uow;
            _context = new ShifterAndWorkerEntities();
        }

        public ActionResult Create()
        {
            User loggedUser = Session["LoggedUser"] as User;

            var users = _uow.UserManager.ListAll(x => x.IsActive && x.StoreId == loggedUser.StoreId).OrderBy(x => x.FirstName).ToList();
            var departments = _uow.DepartmentManager.ListAll(x => x.IsActive && x.StoreId == loggedUser.StoreId).OrderBy(x => x.Name).ToList();
            var breaks = _uow.BreakManager.ListAll(x => x.IsActive).OrderByDescending(x => x.StartTime).ToList();

            ViewData["Users"] = VMUser.Parse(users);
            ViewData["Departments"] = VMDepartment.Parse(departments);
            ViewData["Breaks"] = VMBreak.Parse(breaks);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VMShift model, int[] breakIds)
        {
            #region Logged user

            User loggedUser = Session["LoggedUser"] as User;

            #endregion

            #region Begin transaction

            using (DbContextTransaction dbTran = _context.Database.BeginTransaction())
            {
                try
                {
                    #region Creation shift

                    Shift shift = new Shift
                    {
                        Date = model.Date,
                        StartTime = model.StartTime,
                        EndTime = model.EndTime,
                        UserId = model.UserId,
                        StoreId = loggedUser.StoreId,
                        DepartmentId = model.DepartmentId,
                        CreateDate = DateTime.Now,
                        IsActive = true,
                        IsNotify = false
                    };
                    _uow.ShiftManager.Add(shift);

                    #endregion

                    #region Creation related table between shift and break 

                    for (int i = 0; i < breakIds.Length; i++)
                    {
                        ShiftBreak shiftBreak = new ShiftBreak
                        {
                            BreakId = breakIds[i],
                            ShiftId = shift.ShiftId
                        };
                        _uow.ShiftBreakManager.Add(shiftBreak);
                    }

                    #endregion

                    #region Try to save changes and commit transaction

                    _uow.SaveChanges();
                    dbTran.Commit();

                    #endregion
                }
                catch (Exception e)
                {
                    dbTran.Rollback();

                    TempData["ProcessResult"] = "An unexpected error occured while creating shift.";
                    TempData["AlertType"] = "danger";
                    return RedirectToAction("Create");

                }
            }

            #endregion

            #region Return success result message with TempData

            TempData["ProcessResult"] = "Shift created successfully.";
            TempData["AlertType"] = "success";
            return RedirectToAction("Create");

            #endregion
        }
    }
}

ShifterAndWorker/SAW.UI/Areas/Panel/Views/Shift/Create.cshtml
@using SAW.Model.ViewModel
@model VMShift

@{
    ViewBag.Title = "Create Shift";
    Layout = "~/Areas/Panel/Views/Shared/_Layout.cshtml";

    List<VMUser> users = ViewData["Users"] as List<VMUser>;
    List<VMDepartment> departments = ViewData["Departments"] as List<VMDepartment>;
    List<VMBreak> breaks = ViewData["Breaks"] as List<VMBreak>;
}

<div style="margin: 100px 50px;">
    <div class="header">
        <a class="btn btn-xs btn-dark" href="/Panel/Shift/Preview"><i class="fa fa-arrow-circle-left"></i> Back To Preview</a>
        <h1><strong>Create</strong> Shift</h1>
        <hr />
    </div>
    <div class="row">
        @if (TempData["ProcessResult"] != null)
        {
            <div class="alert alert-@TempData["AlertType"]" role="alert">
                @TempData["ProcessResult"].ToString()
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        <div class="col-lg-12">
            @using (Html.BeginForm("Create", "Shift", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="row m-t-10">
                    <div class="col-xs-3">

                        <div class="form-group">
                            <label class="control-label">Department*</label>
                            @*@Html.DropDownListFor(model => model.DepartmentId, new SelectList(departments, "DepartmentId", "Name"), "Select a department", new { @class = "form-control", required = "true" })*@
                            <select name="DepartmentId" class="form-control" required>
                                @foreach (var department in departments)
                                {
                                    <option value="@department.DepartmentId">@department.Name</option>
                                }
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label">User*</label>
                            @Html.DropDownListFor(model => model.UserId, new SelectList(users, "UserId", "FirstName"), "Select a user", new { @class = "form-control", required = "true" })
                            @*<select name="UserId" class="form-control" required>
                                @foreach (var user in users)
                                {
                                    <option value="@user.UserId">@user.FirstName @user.LastName</option>
                                }
                            </select>*@
                        </div>

                        <div class="form-group">
                            <label class="control-label">Breaks*</label>
                            <select name="BreakIds" class="form-control" multiple>
                                @foreach (var _break in breaks)
                                {
                                    <option value="@_break.BreakId">@_break.StartTime - @_break.EndTime</option>
                                }
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Date*</label>
                            <div class="append-icon">
                                <input type="text" name="date" class="form-control form-white" autocomplete="off" autofocus required />
                                <i class="fa fa-table"></i>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">Start Time*</label>
                            <div class="append-icon">
                                <input type="text" name="startTime" class="form-control form-white" maxlength="5" autocomplete="off" required />
                                <i class="icon-clock"></i>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label">End Time*</label>
                            <div class="append-icon">
                                <input type="text" name="endTime" class="form-control form-white" maxlength="5" autocomplete="off" required />
                                <i class="icon-clock"></i>
                            </div>
                        </div>

                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </span>
                    </div>
                </div>
            }
        </div>
    </div>
</div>